services:
  web:
    build: .
    command: ["deno", "task", "start"]
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
      CACHE_EXPIRATION: 120
    restart: always
  redis:
    image: "redis:6.0"
    restart: always
