services:
  web:
    build: .
    command: ["deno", "task", "start"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      PORT: 8000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOG_LEVEL: INFO
      CACHE_EXPIRATION: 120
      APP_VERSION: dev
      STEAM_REQUEST_DELAY_MS: 0
    restart: always
  redis:
    image: "redis:6.0"
    restart: always
