name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Create Release and Build
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Deno environment
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v2.0.0

    - name: Get Latest Tag
      id: get_latest_tag
      run: |
        git fetch --tags
        TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
        echo "Latest tag: $TAG"
        echo "LATEST_TAG=$TAG" >> $GITHUB_OUTPUT

    - name: Bump Version
      id: bump_version
      run: |
        latest_version=${{ steps.get_latest_tag.outputs.LATEST_TAG }}
        if [[ "$latest_version" == "v0.0.0" ]]; then
          new_version="v1.0.0"
        else
          new_version=$(echo $latest_version | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
        fi
        echo "New version: $new_version"
        echo "NEW_VERSION=$new_version" >> $GITHUB_OUTPUT

    # Create a release using GitHub's release action
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.NEW_VERSION }}
        release_name: Release ${{ steps.bump_version.outputs.NEW_VERSION }}
        draft: false
        prerelease: false

    # Build for macOS (x86)
    - name: Build for macOS (x86)
      run: deno task build_mac_x86

    # Upload macOS (x86) artifact
    - name: Upload macOS (x86) build
      uses: actions/upload-artifact@v3
      with:
        name: steamcmd_mac_amd64
        path: bin/steamcmd_mac_amd64

    # Build for macOS (ARM)
    - name: Build for macOS (ARM)
      run: deno task build_mac_arm

    # Upload macOS (ARM) artifact
    - name: Upload macOS (ARM) build
      uses: actions/upload-artifact@v3
      with:
        name: steamcmd_mac_arm
        path: bin/steamcmd_mac_arm

    # Build for Windows
    - name: Build for Windows (x86_64)
      run: deno task build_win

    # Upload Windows build
    - name: Upload Windows build
      uses: actions/upload-artifact@v3
      with:
        name: steamcmd_win64
        path: bin/steamcmd_win64.exe

    # Build for Linux (x86)
    - name: Build for Linux (x86_64)
      run: deno task build_linux_x86

    # Upload Linux (x86) build
    - name: Upload Linux (x86_64) build
      uses: actions/upload-artifact@v3
      with:
        name: steamcmd_linux_amd64
        path: bin/steamcmd_linux_amd64

    # Build for Linux (ARM)
    - name: Build for Linux (ARM)
      run: deno task build_linux_arm

    # Upload Linux (ARM) build
    - name: Upload Linux (ARM) build
      uses: actions/upload-artifact@v3
      with:
        name: steamcmd_linux_arm
        path: bin/steamcmd_linux_arm

    # Attach artifacts to the GitHub release
    - name: Attach Artifacts to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: |
          bin/steamcmd_mac_amd64
          bin/steamcmd_mac_arm
          bin/steamcmd_win64.exe
          bin/steamcmd_linux_amd64
          bin/steamcmd_linux_arm
        asset_name: |
          steamcmd_mac_amd64
          steamcmd_mac_arm
          steamcmd_win64.exe
          steamcmd_linux_amd64
          steamcmd_linux_arm
        asset_content_type: application/octet-stream
